services:
  redis-db:
    image: redis
    container_name: redis-db
    volumes:
      - redis-data:/data
    networks:
      - redis-net

  backend-dev:
    image: node:18
    container_name: backend-dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run start:dev"
    ports:
      - "5000:5000"
    environment:
      REDIS_HOST: redis-db
      REDIS_PORT: 6379
      NODE_ENV: development
    depends_on:
      - redis-db
    networks:
      - redis-net
#    develop:
#      watch:
#        - action: sync
#          path: ./src
#          target: ./app/src
#          ignore:
#            - node_modules/
##        - action: sync
##          path: ./package.json
##          target: ./package.json

volumes:
  redis-data:

networks:
  redis-net:
    driver: bridge
